version: "3.7"

services:
  fahcontrol:
    build: ./
    network_mode: host
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./FAHClient:/home/fah/.FAHClient
